Added minimum layer definition for Convolutional and Fully Connected
genexuslabs/mlmodel-pattern pull request #6
Opened 2021-02-09 19:38 UTC by mcrispino

2021-02-23 12:04 UTC, jechague requested changes
Marking this as a request for changes although I understand this is WIP

2021-02-23 12:04 UTC, jechague commented on MLModelInstance.xml
> +                </Attribute>
We should be careful of using terminology from Ludwig that is not widely accepted across the ML community. I know they refer to their network's input layers as "encoders" but that term is generally used when working under a Encoder-Decoding architecture (like in an autoencoder)

2021-02-23 12:04 UTC, jechague commented on MLModelInstance.xml
> +                     Caption="{0} Layer"
```suggestion
                     Caption="{0}"
```
This is the change we discussed via email about dropping the "Layer" part of the name of an instance of a layer

2021-02-23 12:15 UTC, mcrispino commented on MLModelInstance.xml
> +                </Attribute>
What name would you suggest?

2021-02-23 12:17 UTC, mcrispino commented on MLModelInstance.xml
> +                           ApplyIf="self::*[@layerType = 'Fully Connected']">
Would it be the same attribute for both layer types, or could we have different attributes for the different layers?

If it is the same attribute, then the name change is fine. But if each layer type will have its own attribute, we can keep the Ludwig's name...

2021-02-23 12:18 UTC, mcrispino commented on MLModelInstance.xml
> +            </Attributes>
Fixed at [f01bf41](https://github.com/genexuslabs/mlmodel-pattern/pull/6/commits/f01bf41b900d4faaf341b56b3f71c96e8cd99647)

2021-02-23 12:18 UTC, mcrispino commented on MLModelInstance.xml
> +                     Caption="{0} Layer"
Take a look at commit [f01bf41](https://github.com/genexuslabs/mlmodel-pattern/pull/6/commits/f01bf41b900d4faaf341b56b3f71c96e8cd99647), removed the "layer" part but added the layer's name to the caption.

2021-02-23 12:24 UTC, jechague commented on MLModelInstance.xml
> +                           ApplyIf="self::*[@layerType = 'Fully Connected']">
They are technically the same concept but named differently depending on whether the layers works on images (where the "filter" name is used) as opposed to tensors of other types (where the "units" name is used). 

The ideal thing would be to have a single attribute whose name changes depending on the layer type but I don't know if that possible here.

Note that the names used for these attributes is not a Ludwig-specific thing but general ML terminology. Furthermore, and as noted on my following comment below, we should minimize, and if possible avoid, using Ludwig-specific terminology

2021-02-23 12:33 UTC, jechague commented on MLModelInstance.xml
> +                </Attribute>
Correct me if I'm wrong, but this attribute represent the input layer of the model, does it not?

If that the case, I think they should not have a name at all as this section of the model should not be separate from the other layers (the one defined under "Layer").

2021-02-23 12:59 UTC, mcrispino commented on MLModelInstance.xml
> +                           ApplyIf="self::*[@layerType = 'Fully Connected']">
If they have different names, we'll need two attributes. This one, `fc_size`, will be available for fully connected layers only, and we can have another attribute, with another name, for LSTMs or other layer types.

2021-02-23 13:01 UTC, mcrispino commented on MLModelInstance.xml
> +                </Attribute>
Ok. Removed the `encoder` attribute at [c75ecf7](https://github.com/genexuslabs/mlmodel-pattern/pull/6/commits/c75ecf7783170e1f1290fddfcbcb83dd1294decf).

2021-02-23 13:04 UTC, jechague commented on MLModelInstance.xml
> +                           ApplyIf="self::*[@layerType = 'Fully Connected']">
Oh, I think I misunderstood your question: my answer was referring to `num_units` (from FC and LSTM layers) and `num_filters` (from CNNs). For both FC and LSTM layers the parameters is the same: `num_units` so we should have a single parameter for both

2021-02-25 14:29 UTC, mcrispino commented on MLModelInstance.xml
> +                           ApplyIf="self::*[@layerType = 'Fully Connected']">
Ok, renamed `fc_size` to `num_units`, at [2facd91](https://github.com/genexuslabs/mlmodel-pattern/pull/6/commits/2facd919226326f45529eb49a6c5a58b63c1d558)

2021-02-25 17:24 UTC, jechague approved these changes
LGTM

2021-02-25 17:42 UTC, merged